STDMV={};local dmvPeds,dmvBlips={},{}
function STDMV.Open()SetNuiFocus(true,true);TriggerServerEvent('st-core:server:dmvData');SendNUIMessage({action='open'})end
function STDMV.OpenInsuranceClaim()SetNuiFocus(true,true);TriggerServerEvent('st-core:server:claims:getVehicles');SendNUIMessage({action='openInsuranceClaim'})end
RegisterNetEvent('st-core:client:openDMV',function()STDMV.Open()end);RegisterNetEvent('st-core:client:openInsuranceClaim',function()STDMV.OpenInsuranceClaim()end);RegisterCommand(Config.DMV.Command or'dmv',function()STDMV.Open()end,false);RegisterCommand('insclaim',function()STDMV.OpenInsuranceClaim()end,false)
local function createDMVBlips()if not Config.DMV.Blip or not Config.DMV.Blip.Enabled then return end;for _,b in ipairs(dmvBlips)do RemoveBlip(b)end;dmvBlips={};for _,l in ipairs(Config.DMV.Locations or{})do local b=AddBlipForCoord(l.x,l.y,l.z);SetBlipSprite(b,Config.DMV.Blip.Sprite or 498);SetBlipDisplay(b,4);SetBlipScale(b,Config.DMV.Blip.Scale or .8);SetBlipColour(b,Config.DMV.Blip.Color or 3);SetBlipAsShortRange(b,true);BeginTextCommandSetBlipName('STRING');AddTextComponentString(Config.DMV.Blip.Name or'Department of Motor Vehicles');EndTextCommandSetBlipName(b);dmvBlips[#dmvBlips+1]=b end end
local function createDMVPeds()local m=joaat(Config.DMV.PedModel or's_m_m_fiboffice_01');RequestModel(m);while not HasModelLoaded(m)do Wait(50)end;for _,p in ipairs(dmvPeds)do if DoesEntityExist(p)then DeletePed(p)end end;dmvPeds={};for _,l in ipairs(Config.DMV.Locations or{})do local p=CreatePed(4,m,l.x,l.y,l.z-1,l.heading or 0,false,false);SetEntityAsMissionEntity(p,true,true);SetEntityInvincible(p,true);FreezeEntityPosition(p,true);SetBlockingOfNonTemporaryEvents(p,true);SetPedCanRagdoll(p,false);TaskStartScenarioInPlace(p,Config.DMV.PedScenario or'WORLD_HUMAN_CLIPBOARD',0,true);dmvPeds[#dmvPeds+1]=p end;SetModelAsNoLongerNeeded(m)end
CreateThread(function()Wait(1000);createDMVBlips();createDMVPeds();while true do local w,c=1000,GetEntityCoords(PlayerPedId());for i,l in ipairs(Config.DMV.Locations or{})do local d= #(c-vector3(l.x,l.y,l.z));if d<15 then w=0;local p=dmvPeds[i];if p and DoesEntityExist(p)and d<(Config.DMV.InteractionDistance or 2)then BeginTextCommandDisplayHelp('STRING');AddTextComponentSubstringPlayerName('Press ~INPUT_CONTEXT~ to speak with the DMV clerk');EndTextCommandDisplayHelp(0,false,true,-1);if IsControlJustReleased(0,38)then STDMV.Open()end end end end;Wait(w)end end)
AddEventHandler('onResourceStop',function(r)if r~=GetCurrentResourceName()then return end;for _,p in ipairs(dmvPeds)do if DoesEntityExist(p)then DeletePed(p)end end;for _,b in ipairs(dmvBlips)do RemoveBlip(b)end;SetNuiFocus(false,false)end)
local reads={load='st-core:server:dmv:getOverview',getOverview='st-core:server:dmv:getOverview',getVehicle='st-core:server:dmv:getVehicle',getTitle='st-core:server:dmv:getTitle',getHistory='st-core:server:dmv:getHistory',getLicense='st-core:server:dmv:getLicense',getAppointments='st-core:server:dmv:getAppointments',bookAppointment='st-core:server:dmv:bookAppointment',cancelAppointment='st-core:server:dmv:cancelAppointment'}
local writes={registerVehicle='st-core:server:registerVehicle',renewRegistration='st-core:server:renewRegistration',buyInsurance='st-core:server:buyInsurance',renewInsurance='st-core:server:renewInsurance',customPlate='st-core:server:customPlate',submitInsuranceClaim='st-core:server:claims:submit'}
RegisterNUICallback('lookupVehicle',function(d,cb)local plate=type(d)=='table'and d.plate or'';exports['qb-core']:GetCoreObject().Functions.TriggerCallback('st-core:server:lookupVehicleByPlate',function(ok,r)if ok then SendNUIMessage({action='result',result={ok=true,message=r.message,data=r.data}})else SendNUIMessage({action='result',result={ok=false,message=r and r.message or'Unable to look up vehicle.'}})end end,{plate=plate});cb({ok=true,pending=true})end)
RegisterNUICallback('request',function(d,cb)local a=type(d)=='table'and d.action;local p=type(d)=='table'and d.data or{};local n=reads[a];if not n then cb({ok=false,error='unknown_action'});return end;exports['qb-core']:GetCoreObject().Functions.TriggerCallback(n,function(ok,r)cb({ok=ok,data=ok and r or nil,error=ok and nil or r})end,p)end)
RegisterNUICallback('mutate',function(d,cb)local a=type(d)=='table'and d.action;local p=type(d)=='table'and d.data or{};local e=writes[a];if not e then cb({ok=false,error='unknown_action'});return end;TriggerServerEvent(e,p);cb({ok=true,pending=true})end)
RegisterNUICallback('close',function(_,cb)SetNuiFocus(false,false);SendNUIMessage({action='close'});cb({ok=true})end)
RegisterNUICallback('saleContractIssue',function(_,cb)TriggerServerEvent('st-core:server:saleContractIssue');cb({ok=true})end)
RegisterNUICallback('saleContractClose',function(_,cb)TriggerServerEvent('st-core:server:saleContractClose');cb({ok=true})end)
RegisterNetEvent('st-core:client:dmvData',function(d)SendNUIMessage({action='data',data=d})end);RegisterNetEvent('st-core:client:dmvResult',function(r)SendNUIMessage({action='result',result=r})end)
RegisterNetEvent('st-core:client:claims:vehicles',function(v)SendNUIMessage({action='claimVehicles',vehicles=v or{}})end);RegisterNetEvent('st-core:client:claims:result',function(ok,r)SendNUIMessage({action='claimResult',success=ok,result=r})end);RegisterNetEvent('st-core:client:claims:list',function(v)SendNUIMessage({action='claimList',claims=v or{}})end);RegisterNetEvent('st-core:client:claims:reviewResult',function(ok,r)SendNUIMessage({action='claimReviewResult',success=ok,result=r})end);RegisterNetEvent('st-core:client:claims:audit',function(ok,r)SendNUIMessage({action='claimAudit',success=ok,result=r})end)
