STDocuments = {}
local function addItem(source,itemName,metadata)
 if GetResourceState('ox_inventory')~='started' then return false,'ox_inventory_not_started' end
 local ok,result=pcall(function() if not exports.ox_inventory:CanCarryItem(source,itemName,1,metadata) then return false end return exports.ox_inventory:AddItem(source,itemName,1,metadata) end)
 if not ok or result==false or result==nil then return false,'item_add_failed' end return true,result
end
local function registrationMetadata(r) return {document_type='vehicle_registration',registration_id=r.id,registration_number=r.registration_number,vehicle_identifier=r.vehicle_identifier,plate=r.plate,plate_type=r.plate_type,owner_identifier=r.owner_identifier,owner_name=r.owner_name,vehicle_model=r.vehicle_model,vehicle_display_name=r.vehicle_display_name,purchase_price=r.purchase_price,dealership=r.dealership,registered_at=r.registered_at,expires_at=r.expires_at,status=r.status,description=('VEHICLE REGISTRATION | %s | %s'):format(r.owner_name or 'Unknown',r.plate or 'N/A')} end
local function insuranceMetadata(p) return {document_type='insurance_card',policy_id=p.id,policy_number=p.policy_number,insurance_company=Config.Insurance.CompanyName,insured_name=p.owner_name or p.insured_name,owner_identifier=p.owner_identifier,vehicle_identifier=p.vehicle_identifier,plate=p.plate,vehicle_model=p.vehicle_model,vehicle_display_name=p.vehicle_display_name,coverage=p.plan_name,coverage_type=p.coverage_type,liability_limit=p.liability_limit,collision_limit=p.collision_limit,comprehensive_limit=p.comprehensive_limit,deductible=p.deductible,premium=p.premium,effective_at=p.effective_at,expires_at=p.expires_at,status=p.status,description=('INSURANCE CARD | %s | %s'):format(p.owner_name or 'Unknown',p.policy_number or 'N/A')} end
local function titleMetadata(t) return {document_type='vehicle_title',title_id=t.id,title_number=t.title_number,vehicle_identifier=t.vehicle_identifier,owner_identifier=t.owner_identifier,owner_name=t.owner_name,title_status=t.title_status,issue_date=t.issue_date,description=('VEHICLE TITLE | %s | %s'):format(t.owner_name or 'Unknown',t.title_number or 'N/A')} end
local function licenseMetadata(l) return {document_type='driver_license',license_id=l.id,license_number=l.license_number,owner_identifier=l.owner_identifier,owner_name=l.owner_name,class=l.class,endorsements=l.endorsements,restrictions=l.restrictions,points=l.points,status=l.status,issued_at=l.issued_at,expires_at=l.expires_at,description=('DRIVER LICENSE | %s | Class %s'):format(l.owner_name or 'Unknown',l.class or 'C')} end
function STDocuments.CreateRegistrationDocument(source,r) if not r then return false,'registration_not_found' end return addItem(source,Config.Documents.RegistrationItem,registrationMetadata(r)) end
function STDocuments.CreateInsuranceCard(source,p) if not p then return false,'policy_not_found' end return addItem(source,Config.Documents.InsuranceCardItem,insuranceMetadata(p)) end
function STDocuments.CreateTitleDocument(source,t) if not t then return false,'title_not_found' end return addItem(source,Config.Documents.TitleItem,titleMetadata(t)) end
function STDocuments.CreateDriverLicense(source,l) if not l then return false,'license_not_found' end return addItem(source,Config.Documents.DriverLicenseItem,licenseMetadata(l)) end
function STDocuments.CreateSaleContract(source,c) if not c then return false,'contract_not_found' end local m={document_type='vehicle_sale_contract',contract_id=c.id,contract_number=c.contract_number,status=c.status,seller_identifier=c.seller_identifier,seller_name=c.seller_name,buyer_identifier=c.buyer_identifier,buyer_name=c.buyer_name,vehicle_identifier=c.vehicle_identifier,vin=c.vin,plate=c.plate,vehicle_model=c.vehicle_model,vehicle_display_name=c.vehicle_display_name,sale_price=c.sale_price,seller_signature=c.seller_signature,buyer_signature=c.buyer_signature,seller_signed_at=c.seller_signed_at,buyer_signed_at=c.buyer_signed_at,issued_at=c.issued_at,expires_at=c.expires_at,description=('VEHICLE SALE CONTRACT | %s | %s'):format(c.contract_number or 'N/A',c.plate or 'N/A')} return addItem(source,Config.Documents.VehicleSaleContractItem,m) end
exports('CreateRegistrationDocument',STDocuments.CreateRegistrationDocument);exports('CreateInsuranceCard',STDocuments.CreateInsuranceCard);exports('CreateTitleDocument',STDocuments.CreateTitleDocument);exports('CreateDriverLicense',STDocuments.CreateDriverLicense);exports('CreateSaleContract',STDocuments.CreateSaleContract)
