const app=document.getElementById('app');
let state={pendingPurchases:[],registrations:[],insurance:[],plans:[],fees:{}};
let contractState=null, drawing=false, canvas=null, ctx=null;
const nui=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const money=n=>`$${Number(n||0).toLocaleString()}`;
const date=v=>{if(!v)return '—';const d=new Date(Number(v)*1000);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString()};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.opacity=1;clearTimeout(window.tt);window.tt=setTimeout(()=>t.style.opacity=0,3000)}
function render(){
 document.getElementById('pending').innerHTML=state.pendingPurchases.length?state.pendingPurchases.map(v=>`<article class="card"><div class="card-head"><div><strong>${esc(v.display_name)}</strong><div class="muted">Purchase awaiting DMV registration</div></div><span class="pill pending-pill">PENDING</span></div><div class="vehicle-grid"><div><small>Temporary plate</small><b>${esc(v.temporary_plate||'—')}</b></div><div><small>Model</small><b>${esc(v.model||'—')}</b></div><div><small>Purchase price</small><b>${money(v.purchase_price)}</b></div><div><small>Purchase type</small><b>${esc(v.purchase_type||'—')}</b></div><div><small>Payment</small><b>${esc(v.payment_method||'—')}</b></div><div><small>Financed</small><b>${v.financed?'Yes':'No'}</b></div></div><div class="row"><span>Dealership</span><span>${esc(v.dealership||'—')}</span></div><div class="row"><span>Purchased</span><span>${date(v.purchased_at)}</span></div><div class="actions"><button class="action" onclick="registerVehicle('${esc(v.vehicle_identifier)}')">Register vehicle</button></div></article>`).join(''):'<div class="empty">No vehicles are waiting for registration.</div>';
 document.getElementById('registrations').innerHTML=state.registrations.length?state.registrations.map(v=>`<article class="card"><div class="card-head"><div><strong>${esc(v.vehicle_display_name||v.vehicle_model||'Registered vehicle')}</strong><div class="muted">Owner: ${esc(v.owner_name||'Unknown')}</div></div><span class="pill ${v.status==='active'?'active-pill':'warning-pill'}">${esc((v.status||'').toUpperCase())}</span></div><div class="vehicle-grid"><div><small>Plate</small><b>${esc(v.plate)}</b></div><div><small>VIN</small><b>${esc(v.vin||'—')}</b></div><div><small>Registration</small><b>${date(v.expires_at)}</b></div><div><small>Purchase price</small><b>${money(v.purchase_price)}</b></div><div><small>Dealer</small><b>${esc(v.dealership||'—')}</b></div><div><small>Financed</small><b>${v.financed?'Yes':'No'}</b></div></div><div class="actions"><button class="action" onclick="renewRegistration('${esc(v.vehicle_identifier)}')">Renew registration</button><button class="action secondary" onclick="customPlate('${esc(v.vehicle_identifier)}')">Custom plate</button></div></article>`).join(''):'<div class="empty">No registered vehicles found.</div>';
 document.getElementById('insuranceCards').innerHTML=state.insurance.length?state.insurance.map(p=>`<article class="card"><div class="card-head"><div><strong>${esc(p.policy_number)}</strong><div class="muted">${esc(p.plate||p.vehicle_identifier||'')}</div></div><span class="pill ${p.status==='active'?'active-pill':'warning-pill'}">${esc((p.status||'').toUpperCase())}</span></div><div class="row"><span>Coverage</span><span>${esc(p.plan_name||'Unknown')}</span></div><div class="row"><span>Liability</span><span>${money(p.liability_limit)}</span></div><div class="row"><span>Collision</span><span>${money(p.collision_limit)}</span></div><div class="row"><span>Comprehensive</span><span>${money(p.comprehensive_limit)}</span></div><div class="row"><span>Deductible</span><span>${money(p.deductible)}</span></div><div class="row"><span>Monthly premium</span><b>${money(p.premium)}</b></div><div class="row"><span>Expires</span><span>${date(p.expires_at)}</span></div><div class="actions"><button class="action" onclick="renewInsurance('${esc(p.vehicle_identifier)}')">Renew policy</button></div></article>`).join(''):'<div class="empty">No insurance policies found.</div>';
 document.getElementById('plans').innerHTML=state.plans.map(p=>`<article class="plan"><h3>${esc(p.name)}</h3><div class="muted">${esc(p.description)}</div><div class="price">${money(p.monthly_premium)}<small>/month</small></div><div class="row"><span>Liability</span><span>${money(p.liability_limit)}</span></div><div class="row"><span>Collision</span><span>${money(p.collision_limit)}</span></div><div class="row"><span>Comprehensive</span><span>${money(p.comprehensive_limit)}</span></div><div class="row"><span>Deductible</span><span>${money(p.deductible)}</span></div><div class="actions"><button class="action" onclick="buyInsurance('${esc(p.id)}')">Choose plan</button></div></article>`).join('');
}
function registerVehicle(id){const custom=prompt('Custom plate? Leave blank for a standard AAA 000 plate.');nui('registerVehicle',{vehicleIdentifier:id,customPlate:custom||null})}
function renewRegistration(id){nui('renewRegistration',{vehicleIdentifier:id})}
function customPlate(id){const plate=prompt('Enter your custom plate (max 8 characters):');if(plate)nui('customPlate',{vehicleIdentifier:id,plate})}
function buyInsurance(planId){const id=prompt('Enter the vehicle identifier to insure:');if(id)nui('buyInsurance',{vehicleIdentifier:id,planId})}
function renewInsurance(id){nui('renewInsurance',{vehicleIdentifier:id})}
function issueSaleContract(){nui('saleContractIssue')}

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
document.getElementById('close').onclick=()=>nui('close');
document.getElementById('contractClose').onclick=()=>{document.getElementById('contractOverlay').classList.add('hidden');nui('saleContractClose')};
window.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!document.getElementById('contractOverlay').classList.contains('hidden')){document.getElementById('contractOverlay').classList.add('hidden');nui('saleContractClose')}else nui('close')}});

function contractField(label,value){return `<div class="contract-field"><small>${label}</small><strong>${esc(value||'—')}</strong></div>`}
function setupSignature(){canvas=document.getElementById('signaturePad');if(!canvas)return;ctx=canvas.getContext('2d');ctx.lineWidth=2.5;ctx.lineCap='round';ctx.lineJoin='round';const pos=e=>{const r=canvas.getBoundingClientRect();const p=e.touches?e.touches[0]:e;return {x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height}};canvas.onpointerdown=e=>{drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};canvas.onpointermove=e=>{if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke()};window.onpointerup=()=>drawing=false;document.getElementById('clearSignature').onclick=()=>ctx.clearRect(0,0,canvas.width,canvas.height)}
function signatureBlank(){if(!canvas)return true;const d=ctx.getImageData(0,0,canvas.width,canvas.height).data;for(let i=3;i<d.length;i+=4)if(d[i]>10)return false;return true}
function openContract(contract){contractState=contract;const overlay=document.getElementById('contractOverlay'),body=document.getElementById('contractBody');overlay.classList.remove('hidden');document.getElementById('contractStatus').textContent=contract.status==='draft'?'Seller signature required':contract.status==='seller_signed'?'Awaiting buyer signature':'Completed — ownership transferred';
 const common=`<div class="contract-number">Contract ${esc(contract.contractNumber)}</div><div class="contract-section"><h3>Vehicle</h3><div class="contract-grid">${contractField('Vehicle',contract.vehicleDisplayName||contract.vehicleModel)}${contractField('VIN',contract.vin)}${contractField('Plate',contract.plate)}${contractField('Vehicle ID',contract.vehicleIdentifier)}</div></div><div class="contract-section"><h3>Parties</h3><div class="contract-grid">${contractField('Seller',contract.sellerName)}${contractField('Buyer',contract.buyerName)}${contractField('Contract expires',date(contract.expiresAt))}</div></div>`;
 let html=common;
 if(contract.status==='draft')html+=`<div class="contract-section"><h3>Sale terms</h3><label class="form-label">Agreed sale price<input id="salePrice" type="number" min="1" step="1" value="${Number(contract.salePrice||0)}"></label><p class="legal">By signing, the seller confirms they are voluntarily selling the vehicle described above to the named buyer for the amount entered.</p><h3>Seller signature</h3><canvas id="signaturePad" width="700" height="180"></canvas><div class="signature-actions"><button class="action secondary" id="clearSignature">Clear</button><button class="action" onclick="submitSellerSignature()">Sign contract</button></div></div>`;
 else html+=`<div class="contract-section"><h3>Agreed sale price</h3><div class="sale-price">${money(contract.salePrice)}</div><div class="signature-block"><div><h3>Seller signature</h3>${contract.sellerSignature?`<img src="${contract.sellerSignature}" class="signature-image">`: '<div class="unsigned">Unsigned</div>'}</div><div><h3>Buyer signature</h3>${contract.buyerSignature?`<img src="${contract.buyerSignature}" class="signature-image">`:'<div id="buyerSignArea"><canvas id="signaturePad" width="700" height="180"></canvas><div class="signature-actions"><button class="action secondary" id="clearSignature">Clear</button><button class="action" onclick="submitBuyerSignature()">Sign &amp; transfer ownership</button></div></div>'}</div></div><p class="legal">${contract.buyerSignature?'This contract has been completed. Ownership was transferred only after both signatures were validated by the DMV.':'The buyer must sign this document to complete the transfer. Pressing Enter without a signature does not transfer ownership.'}</p></div>`;
 body.innerHTML=html;setTimeout(setupSignature,0)}
function submitSellerSignature(){if(signatureBlank())return toast('Please sign the contract before continuing.');const price=Number(document.getElementById('salePrice').value);if(!price||price<=0)return toast('Enter a valid sale price.');nui('saleContractSellerSign',{contractId:contractState.id,salePrice:price,signature:canvas.toDataURL('image/png')})}
function submitBuyerSignature(){if(signatureBlank())return toast('Please sign as the buyer.');nui('saleContractBuyerSign',{contractId:contractState.id,signature:canvas.toDataURL('image/png'),sellerServerId:contractState.sellerServerId})}

window.addEventListener('message',e=>{const m=e.data;if(m.action==='open'){app.classList.remove('hidden');nui('load')}if(m.action==='close')app.classList.add('hidden');if(m.action==='data'){if(m.data.refresh){nui('load');return}state={...state,...m.data};render()}if(m.action==='result'){toast(m.result.message||'Request completed');if(m.result.ok)nui('load')}if(m.action==='saleContract'){openContract(m.contract)}if(m.action==='saleContractResult'){toast(m.result.message||'Request completed');if(m.result.ok&&m.result.data)openContract(m.result.data)}});
