const app=document.getElementById('app');let state={pendingPurchases:[],registrations:[],insurance:[],plans:[],fees:{}};
const nui=(name,data={})=>fetch(`https://${GetParentResourceName()}/${name}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
const money=n=>`$${Number(n||0).toLocaleString()}`;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.style.opacity=1;clearTimeout(window.tt);window.tt=setTimeout(()=>t.style.opacity=0,2600)}
function render(){
 document.getElementById('pending').innerHTML=state.pendingPurchases.length?state.pendingPurchases.map(v=>`<article class="card"><strong>${esc(v.display_name)}</strong><div class="muted">${esc(v.vehicle_identifier)}</div><div class="row"><span>Purchase price</span><b>${money(v.purchase_price)}</b></div><div class="actions"><button class="action" onclick="registerVehicle('${esc(v.vehicle_identifier)}')">Register vehicle</button></div></article>`).join(''):'<div class="empty">No vehicles are waiting for registration.</div>';
 document.getElementById('registrations').innerHTML=state.registrations.length?state.registrations.map(v=>`<article class="card"><strong>${esc(v.plate)}</strong><div class="muted">${esc(v.vehicle_identifier)}</div><div class="row"><span>Plate type</span><span>${esc(v.plate_type)}</span></div><div class="row"><span>Status</span><span>${esc(v.status)}</span></div><div class="actions"><button class="action" onclick="renewRegistration('${esc(v.vehicle_identifier)}')">Renew</button><button class="action secondary" onclick="customPlate('${esc(v.vehicle_identifier)}')">Custom plate</button></div></article>`).join(''):'<div class="empty">No registered vehicles found.</div>';
 document.getElementById('insuranceCards').innerHTML=state.insurance.length?state.insurance.map(p=>`<article class="card"><strong>${esc(p.policy_number)}</strong><div class="muted">${esc(p.vehicle_identifier)} · ${esc(p.status)}</div><div class="row"><span>Coverage</span><span>${esc(p.plan_name||'Unknown')}</span></div><div class="row"><span>Monthly premium</span><b>${money(p.premium)}</b></div><div class="row"><span>Expires</span><span>${esc(p.expires_at||'')}</span></div><div class="actions"><button class="action" onclick="renewInsurance('${esc(p.vehicle_identifier)}')">Renew policy</button></div></article>`).join(''):'<div class="empty">No insurance policies found.</div>';
 document.getElementById('plans').innerHTML=state.plans.map(p=>`<article class="plan"><h3>${esc(p.name)}</h3><div class="muted">${esc(p.description)}</div><div class="price">${money(p.monthly_premium)}<small>/month</small></div><div class="row"><span>Liability</span><span>${money(p.liability_limit)}</span></div><div class="row"><span>Collision</span><span>${money(p.collision_limit)}</span></div><div class="row"><span>Comprehensive</span><span>${money(p.comprehensive_limit)}</span></div><div class="row"><span>Deductible</span><span>${money(p.deductible)}</span></div><div class="actions"><button class="action" onclick="buyInsurance('${esc(p.id)}')">Choose plan</button></div></article>`).join('');
}
function registerVehicle(id){const custom=prompt('Custom plate? Leave blank for a standard AAA 000 plate.');nui('registerVehicle',{vehicleIdentifier:id,customPlate:custom||null})}
function renewRegistration(id){nui('renewRegistration',{vehicleIdentifier:id})}
function customPlate(id){const plate=prompt('Enter your custom plate (max 8 characters):');if(plate)nui('customPlate',{vehicleIdentifier:id,plate})}
function buyInsurance(planId){const id=prompt('Enter the vehicle identifier to insure:');if(id)nui('buyInsurance',{vehicleIdentifier:id,planId})}
function renewInsurance(id){nui('renewInsurance',{vehicleIdentifier:id})}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});
document.getElementById('close').onclick=()=>nui('close');
window.addEventListener('keydown',e=>{if(e.key==='Escape')nui('close')});
window.addEventListener('message',e=>{const m=e.data;if(m.action==='open'){app.classList.remove('hidden');nui('load')}if(m.action==='close')app.classList.add('hidden');if(m.action==='data'){if(m.data.refresh){nui('load');return}state={...state,...m.data};render()}if(m.action==='result'){toast(m.result.message||'Request completed');if(m.result.ok)nui('load')}});
